[package]
name = "mokuroku"
version = "0.1.0"
authors = ["Shorakie <mhmdamin.jafari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.1.0"
dotenv = "0.15"
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
serenity = "0.10"

[dependencies.tokio]
version = "1.0"
features = ["macros", "signal", "rt-multi-thread"]